const stations = {
	"ABQ": "Albuquerque",
	"ACA": "Antioch–Pittsburg",
	"ACD": "Arcadia Valley",
	"ADM": "Ardmore",
	"AKY": "Ashland",
	"ALB": "Albany–Rensselaer",
	"ALC": "Alliance",
	"ALD": "Alderson",
	"ALI": "Albion",
	"ALN": "Alton",
	"ALP": "Alpine",
	"ALT": "Altoona",
	"ALX": "Alexandria",
	"ALY": "Albany",
	"AMS": "Amsterdam",
	"ANA": "Anaheim",
	"ARB": "Ann Arbor",
	"ARD": "Ardmore",
	"ARK": "Arkadelphia",
	"ARN": "Auburn",
	"ASD": "Ashland",
	"AST": "Aldershot",
	"ATL": "Atlanta Peachtree",
	"ATN": "Anniston",
	"ATR": "Atmore",
	"AUS": "Austin",
	"BAL": "Baltimore Penn",
	"BAM": "Bangor",
	"BAR": "Barstow",
	"BAS": "Bay St. Louis",
	"BBY": "Boston Back Bay",
	"BCV": "Burke Centre",
	"BEL": "Bellingham Fairhaven",
	"BEN": "Benson",
	"BER": "Berlin",
	"BFD": "Bakersfield",
	"BFX": "Buffalo–Exchange Street",
	"BHM": "Birmingham",
	"BIX": "Biloxi",
	"BKY": "Berkeley",
	"BLF": "Bellows Falls",
	"BMT": "Beaumont",
	"BNC": "Burlington",
	"BNG": "Bingen–White Salmon",
	"BNL": "Bloomington–Normal",
	"BON": "Boston North",
	"BOS": "Boston South",
	"BRA": "Brattleboro",
	"BRH": "Brookhaven",
	"BRK": "Brunswick",
	"BRL": "Burlington",
	"BRO": "Browning",
	"BRP": "Bridgeport",
	"BTL": "Battle Creek",
	"BUF": "Buffalo–Depew",
	"BUR": "Burbank Airport",
	"BWI": "BWI Thurgood Marshall Airport",
	"BYN": "Bryan",
	"CAM": "Camden",
	"CBR": "Cleburne",
	"CBS": "Columbus",
	"CDL": "Carbondale",
	"CEN": "Centralia",
	"CHI": "Chicago Union",
	"CHM": "Champaign–Urbana",
	"CHS": "Charleston",
	"CHW": "Charleston",
	"CIC": "Chico",
	"CIN": "Cincinnati",
	"CIP": "Chipley",
	"CLA": "Claremont",
	"CLB": "Columbia",
	"CLE": "Cleveland",
	"CLF": "Clifton Forge",
	"CLP": "Culpeper",
	"CLT": "Charlotte",
	"CML": "Camarillo",
	"CMO": "Chemult",
	"CNL": "Allensworth State Park",
	"CNV": "Castleton",
	"COC": "Corcoran",
	"COI": "Connersville",
	"COT": "Coatesville",
	"COV": "Connellsville",
	"COX": "Colfax",
	"CPN": "Carpinteria",
	"CRF": "Crawfordsville",
	"CRN": "Creston",
	"CRT": "Croton–Harmon",
	"CRV": "Carlinville",
	"CSN": "Clemson",
	"CSV": "Crestview",
	"CTL": "Centralia",
	"CUM": "Cumberland",
	"CUT": "Cut Bank",
	"CVS": "Charlottesville",
	"CWH": "Cornwells Heights",
	"CWT": "Chatsworth",
	"CYN": "Cary",
	"DAL": "Dallas",
	"DAN": "Danville",
	"DAV": "Davis",
	"DDG": "Dodge City",
	"DEM": "Deming",
	"DEN": "Denver",
	"DER": "Dearborn",
	"DET": "Detroit",
	"DFB": "Deerfield Beach",
	"DHM": "Durham–UNH",
	"DIL": "Dillon",
	"DLB": "Delray Beach",
	"DLD": "DeLand",
	"DLK": "Detroit Lakes",
	"DNC": "Durham",
	"DNK": "Denmark",
	"DOA": "Dowagiac",
	"DOV": "Dover",
	"DOW": "Downingtown",
	"DQN": "Du Quoin",
	"DRD": "Durand",
	"DRT": "Del Rio",
	"DUN": "Dunsmuir",
	"DVL": "Devils Lake",
	"DWT": "Dwight",
	"DYE": "Dyer",
	"EDM": "Edmonds",
	"EFG": "Effingham",
	"EKH": "Elkhart",
	"ELK": "Elko",
	"ELP": "El Paso",
	"ELT": "Elizabethtown",
	"ELY": "Elyria",
	"EMY": "Emeryville",
	"EPH": "Ephrata",
	"ERI": "Erie",
	"ESM": "Essex",
	"ESX": "Essex Junction",
	"EUG": "Eugene–Springfield",
	"EVR": "Everett",
	"EWR": "Newark Liberty International Airport",
	"EXR": "Exeter",
	"EXT": "Exton",
	"FAR": "Fargo",
	"FAY": "Fayetteville",
	"FBG": "Fredericksburg",
	"FED": "Fort Edward",
	"FFV": "Fairfield–Vacaville",
	"FLG": "Flagstaff",
	"FLN": "Flint",
	"FLO": "Florence",
	"FMD": "Fort Madison",
	"FMG": "Fort Morgan",
	"FMT": "Fremont",
	"FNO": "Fresno",
	"FRA": "Framingham",
	"FRE": "Freeport",
	"FTC": "Ticonderoga",
	"FTL": "Fort Lauderdale",
	"FTN": "Fulton",
	"FTW": "Fort Worth",
	"FUL": "Fullerton",
	"GAC": "Santa Clara – Great America",
	"GAS": "Gastonia",
	"GBB": "Galesburg",
	"GCK": "Garden City",
	"GDL": "Glendale",
	"GFD": "Greenfield",
	"GFK": "Grand Forks",
	"GGW": "Glasgow",
	"GJT": "Grand Junction",
	"GLE": "Gainesville",
	"GLM": "Gilman",
	"GLN": "Glenview",
	"GLP": "Gallup",
	"GMS": "Grimsby",
	"GNB": "Greensburg",
	"GNS": "Gainesville",
	"GPK": "East Glacier Park",
	"GRA": "Granby",
	"GRI": "Green River",
	"GRO": "Greensboro",
	"GRR": "Grand Rapids",
	"GRV": "Greenville",
	"GSC": "Glenwood Springs",
	"GTA": "Goleta",
	"GUA": "Guadalupe",
	"GUF": "Gulfport",
	"GVB": "Grover Beach",
	"GWD": "Greenwood",
	"HAM": "Hamlet",
	"HAR": "Harrisburg",
	"HAS": "Hastings",
	"HAV": "Havre",
	"HAY": "Hayward",
	"HAZ": "Hazlehurst",
	"HBG": "Hattiesburg",
	"HEM": "Hermann",
	"HER": "Helper",
	"HFD": "Hartford",
	"HFY": "Harpers Ferry",
	"HGD": "Huntingdon",
	"HHL": "Haverhill",
	"HIN": "Hinton",
	"HLD": "Holdrege",
	"HLK": "Holyoke",
	"HMD": "Hammond",
	"HMI": "Hammond/Whiting",
	"HMW": "Homewood",
	"HNF": "Hanford",
	"HOL": "Hollywood",
	"HOM": "Holland",
	"HOP": "Hope",
	"HOS": "Houston",
	"HPT": "High Point",
	"HUD": "Hudson",
	"HUN": "Huntington",
	"HUT": "Hutchinson",
	"IDP": "Independence",
	"IND": "Indianapolis",
	"IRV": "Irvine",
	"JAN": "Jackson",
	"JAX": "Jacksonville",
	"JEF": "Jefferson City",
	"JOL": "Joliet",
	"JSP": "Jesup",
	"JST": "Johnstown",
	"JXN": "Jackson",
	"KAL": "Kalamazoo",
	"KAN": "Kannapolis",
	"KCY": "Kansas City",
	"KEE": "Kewanee",
	"KEL": "Kelso",
	"KFS": "Klamath Falls",
	"KIN": "Kingston",
	"KIS": "Kissimmee",
	"KKI": "Kankakee",
	"KNG": "Kingman",
	"KTR": "Kingstree",
	"KWD": "Kirkwood",
	"LAB": "Latrobe",
	"LAF": "Lafayette",
	"LAG": "La Grange Road",
	"LAJ": "La Junta",
	"LAK": "Lakeland",
	"LAP": "La Plata",
	"LAU": "Laurel",
	"LAX": "Los Angeles Union",
	"LCH": "Lake Charles",
	"LCN": "Lincoln",
	"LDB": "Lordsburg",
	"LEC": "Lake City",
	"LEE": "Lee's Summit",
	"LEW": "Lewistown",
	"LEX": "Lexington",
	"LFT": "Lafayette",
	"LIB": "Libby",
	"LKL": "Lakeland",
	"LMR": "Lamar",
	"LMY": "Lamy",
	"LNC": "Lancaster",
	"LNK": "Lincoln",
	"LNS": "East Lansing",
	"LOD": "Lodi",
	"LOR": "Lorton",
	"LPE": "Lapeer",
	"LPS": "Lompoc–Surf",
	"LRC": "Lawrence",
	"LRK": "Little Rock",
	"LSE": "La Crosse",
	"LSV": "Las Vegas",
	"LVW": "Longview",
	"LWA": "Leavenworth",
	"LYH": "Lynchburg–Kemper Street",
	"MAC": "Macomb",
	"MAD": "Madera",
	"MAL": "Malta",
	"MAT": "Mattoon",
	"MAY": "Maysville",
	"MCB": "McComb",
	"MCD": "Merced",
	"MCG": "McGregor",
	"MCI": "Michigan City",
	"MCK": "McCook",
	"MDN": "Meriden",
	"MDO": "Madison",
	"MDT": "Mendota",
	"MEI": "Meridian",
	"MEM": "Memphis Central",
	"MET": "Metropark",
	"MHL": "Marshall",
	"MIA": "Miami",
	"MID": "Middletown",
	"MIN": "Mineola",
	"MJY": "Mount Joy",
	"MKA": "Milwaukee Airport",
	"MKE": "Milwaukee",
	"MKS": "Marks",
	"MNG": "Montgomery",
	"MOD": "Modesto",
	"MOE": "Mobile",
	"MOT": "Minot",
	"MPK": "Moorpark",
	"MPR": "Montpelier",
	"MRB": "Martinsburg",
	"MRC": "Maricopa",
	"MSP": "St. Paul - Minneapolis Union",
	"MSS": "Manassas",
	"MTP": "Mount Pleasant",
	"MTR": "Montreal",
	"MTZ": "Martinez",
	"MVN": "Malvern",
	"MVW": "Mount Vernon",
	"MYS": "Mystic",
	"NBK": "New Brunswick",
	"NBN": "Newbern–Dyersburg",
	"NBU": "New Buffalo",
	"NCR": "New Carrollton",
	"NDL": "Needles",
	"NEW": "Newton",
	"NFK": "Norfolk",
	"NFL": "Niagara Falls",
	"NFS": "Niagara Falls",
	"NHT": "Northampton",
	"NHV": "New Haven Union",
	"NIB": "New Iberia",
	"NLC": "New London",
	"NLS": "Niles",
	"NOL": "New Orleans",
	"NOR": "Norman",
	"NPN": "Newport News",
	"NPV": "Naperville",
	"NRK": "Newark",
	"NRO": "New Rochelle",
	"NSF": "North Carolina State Fair",
	"NWK": "Newark Penn",
	"NYF": "New York State Fair",
	"NYP": "New York Penn",
	"OAC": "Oakland Coliseum",
	"OKC": "Oklahoma City",
	"OKE": "Okeechobee",
	"OKJ": "Oakland–Jack London Square",
	"OKL": "Oakville",
	"OLT": "San Diego Old Town",
	"OMA": "Omaha",
	"ONA": "Ontario",
	"ORB": "Old Orchard Beach",
	"ORC": "Oregon City",
	"ORL": "Orlando",
	"OSB": "Old Saybrook",
	"OSC": "Osceola",
	"OSD": "Oceanside",
	"OTM": "Ottumwa",
	"OWL": "Olympia–Lacey",
	"OXN": "Oxnard",
	"PAG": "Pascagoula",
	"PAK": "Palatka",
	"PAO": "Paoli",
	"PAR": "Parkesburg",
	"PBF": "Poplar Bluff",
	"PCT": "Princeton",
	"PDX": "Portland",
	"PGH": "Pittsburgh",
	"PHL": "Philadelphia 30th Street",
	"PHN": "Philadelphia North",
	"PIC": "Picayune",
	"PIT": "Pittsfield",
	"PJC": "Princeton Junction",
	"PLB": "Plattsburgh",
	"PLO": "Plano",
	"PNS": "Pensacola",
	"PNT": "Pontiac",
	"POG": "Portage",
	"POH": "Port Henry",
	"PON": "Pontiac",
	"POR": "Portland",
	"POS": "Pomona",
	"POU": "Poughkeepsie",
	"PRB": "Paso Robles",
	"PRC": "Prince",
	"PRK": "Port Kent",
	"PRO": "Provo",
	"PSC": "Pasco",
	"PSN": "Palm Springs",
	"PTB": "Petersburg",
	"PTH": "Port Huron",
	"PUR": "Purcell",
	"PVD": "Providence",
	"PVL": "Pauls Valley",
	"QAN": "Quantico",
	"QCY": "Quincy",
	"RAT": "Raton",
	"RDD": "Redding",
	"RDW": "Red Wing",
	"REN": "Rensselaer",
	"RGH": "Raleigh Union",
	"RHI": "Rhinecliff–Kingston",
	"RIC": "Richmond",
	"RIV": "Riverside",
	"RKV": "Rockville",
	"RLN": "Rocklin",
	"RMT": "Rocky Mount",
	"RNK": "Roanoke",
	"RNO": "Reno",
	"ROC": "Rochester",
	"ROM": "Rome",
	"ROY": "Royal Oak",
	"RPH": "Randolph",
	"RSP": "Rouses Point",
	"RSV": "Roseville",
	"RTE": "Westwood–Route 128",
	"RTL": "Rantoul",
	"RUD": "Rutland",
	"RUG": "Rugby",
	"RVM": "Richmond Main Street",
	"RVR": "Richmond Staples Mill Road",
	"SAB": "St. Albans",
	"SAC": "Sacramento",
	"SAL": "Salisbury",
	"SAN": "San Diego Santa Fe Depot",
	"SAO": "Saco–Biddeford",
	"SAR": "Saratoga Springs",
	"SAS": "San Antonio",
	"SAV": "Savannah",
	"SBA": "Santa Barbara",
	"SBG": "Sebring",
	"SBY": "Shelby",
	"SCA": "St. Catharines",
	"SCC": "Santa Clara",
	"SCD": "St. Cloud",
	"SCH": "Schriever",
	"SDL": "Slidell",
	"SDY": "Schenectady",
	"SEA": "Seattle King Street",
	"SED": "Sedalia",
	"SFA": "Sanford",
	"SIM": "Simi Valley",
	"SJC": "San Jose Diridon",
	"SJM": "St. Joseph–Benton Harbor",
	"SKN": "Stockton San Joaquin Street",
	"SKT": "Stockton Downtown",
	"SKY": "Sandusky",
	"SLC": "Salt Lake City",
	"SLM": "Salem",
	"SLO": "San Luis Obispo",
	"SLQ": "Saint-Lambert",
	"SMC": "San Marcos",
	"SMT": "Summit",
	"SNA": "Santa Ana",
	"SNB": "San Bernardino",
	"SNC": "San Juan Capistrano",
	"SND": "Sanderson",
	"SNP": "San Clemente Pier",
	"SNS": "Salinas",
	"SOB": "South Bend",
	"SOL": "Solana Beach",
	"SOP": "Southern Pines",
	"SPB": "Spartanburg",
	"SPG": "Springfield",
	"SPI": "Springfield",
	"SPK": "Spokane",
	"SPL": "Staples",
	"SPM": "South Portsmouth–South Shore",
	"SPT": "Sandpoint",
	"SSM": "Selma",
	"STA": "Staunton",
	"STL": "St. Louis Gateway",
	"STM": "Stamford",
	"STN": "Stanley",
	"STS": "New Haven State Street",
	"STW": "Stanwood",
	"SUI": "Suisun–Fairfield",
	"SVT": "Sturtevant",
	"SYR": "Syracuse",
	"TAC": "Tacoma Dome",
	"TAY": "Taylor",
	"TCA": "Toccoa",
	"TCL": "Tuscaloosa",
	"THN": "Thurmond",
	"TLH": "Tallahassee",
	"TOH": "Tomah",
	"TOL": "Toledo",
	"TOP": "Topeka",
	"TPA": "Tampa",
	"TPL": "Temple",
	"TRE": "Trenton",
	"TRI": "Trinidad",
	"TRK": "Turlock–Denair",
	"TRM": "Troy",
	"TRU": "Truckee",
	"TUK": "Tukwila",
	"TUS": "Tucson",
	"TWO": "Toronto Union",
	"TXA": "Texarkana",
	"TYR": "Tyrone",
	"UCA": "Utica",
	"VAC": "Vancouver Pacific Central",
	"VAN": "Vancouver",
	"VEC": "Ventura",
	"VNC": "Van Nuys",
	"VRV": "Victorville",
	"WAB": "Waterbury–Stowe",
	"WAC": "Wasco",
	"WAH": "Washington",
	"WAR": "Warrensburg",
	"WAS": "Washington Union",
	"WBG": "Williamsburg",
	"WDB": "Woodbridge",
	"WDL": "Wisconsin Dells",
	"WEM": "Wells",
	"WEN": "Wenatchee",
	"WFD": "Wallingford",
	"WFH": "Whitefish",
	"WGL": "West Glacier",
	"WHL": "Whitehall",
	"WIH": "Wishram",
	"WIL": "Wilmington",
	"WIN": "Winona",
	"WIP": "Fraser–Winter Park",
	"WLN": "Wilson",
	"WLO": "Winslow",
	"WLY": "Westerly",
	"WND": "Windsor",
	"WNL": "Windsor Locks",
	"WNM": "Windsor–Mt. Ascutney",
	"WNN": "Winnemucca",
	"WNR": "Walnut Ridge",
	"WOB": "Woburn–Anderson",
	"WOR": "Worcester",
	"WPB": "West Palm Beach",
	"WPK": "Winter Park",
	"WPR": "Winter Park Resort",
	"WPT": "Wolf Point",
	"WRJ": "White River Junction",
	"WSP": "Westport",
	"WSS": "White Sulphur Springs",
	"WTH": "Winter Haven",
	"WTI": "Waterloo",
	"WTN": "Williston",
	"YAZ": "Yazoo City",
	"YEM": "Yemassee",
	"YNY": "Yonkers",
	"YUM": "Yuma"
}

const answers = ["ATL","MKS","DLK","SPK","GCK","DRD","SBG","PGH","YEM","HAZ","PNT","FTL","MYS","MOE","AST","LAK","RUG","LPS","SLC","MPK","PBF","ALI","WGL","LKL","NWK","LOR","ATN","BRH","OAC","EVR","RGH","WDL","ROM","OWL","DLB","SNC","BOS","NHT","ELY","LAP","PRC","CDL","WLY","TRK","YNY","MSP","NIB","GWD","HFD","EFG","PON","SNA","ELP","KCY","UCA","HER","OTM","PRK","GRO","DOV","SCD","WNN","BRL","PSN","WSS","WTI","ARD","PJC","IND","CNV","DAN","BEN","GRR","PVL","ACD","LAG","SCC","SED","RVM","AKY","TAC","NFL","BIX","WIL","BCV","GGW","HUD","MEM","NPV","MAY","PRB","WPR","CRT","PTH","TPL","SPB","KEL","CHI","BFD","ADM","HAR","KKI","MDO","HLD","LAJ","COI","ROY","SPI","MEI","DRT","KFS","POS","KNG","PLB","CBR","WPB","TYR","GDL","CLT","BER","SOP","LCN","COT","PIT","DUN","YAZ","STN","WOR","LEE","JXN","LEC","HOL","MDT","COC","EUG","GFK","DHM","CWH","CUM","GMS","ACA","CRV","LSV","SJM","IRV","WDB","FFV","POH","TOH","SBA","JEF","MCB","SAO","SUI","ELK","NOR","PHL","DOW","ASD","NFK","DNC","TOP","SLM","PTB","FTN","TOL","WBG","FBG","SPT","SAL","RSP","POU","FMD","PAO","RLN","MNG","CHM","JOL","CLP","OLT","OKJ","RDD","SAB","MCI","LDB","TLH","FTC","YUM","NBU","HAY","BON","GTA","CEN","POG","WAR","MAL","CAM","LAU","DFB","MIA","LEX","WEN","BTL","CIP","SAS","NFS","STA","DOA","EPH","LRK","FTW","NBN","CHW","HMI","OSC","ALY","GUF","WAH","GNB","ORL","WIN","STL","CIC","SNP","NPN","KIN","SFA","DNK","OMA","SEA","LYH","BKY","AMS","FUL","PAR","SMC","JST","PVD","CIN","DER","ONA","MTP","BNG","ABQ","RDW","MAC","HMW","CLE","FLO","CWT","CBS","HUT","MJY","SLQ","GAC","ERI","WOB","ORC","SPM","CHS","BNC","FMG","NEW","WSP","CMO","FLG","BHM","BYN","JSP","RPH","RHI","RIV","ARN","WNM","LAB","OSB","SJC","BAM","WND","ALB","MPR","RIC","BRA","BAR","SPG","HEM","CSN","HMD","SAV","TAY","FAR","MKE","NYF","DWT","TRU","MVW","PRO","EWR","BNL","OSD","LCH","RUD","TPA","KWD","ALC","HGD","MCK","MOT","SNB","GVB","BRP","LSE","MTR","FRE","HLK","RMT","PDX","NDL","BAS","LIB","HPT","CLB","GLP","ORB","CTL","NBK","PNS","LMR","PHN","NYP","PLO","EDM","CSV","WFH","WIH","FRA","SNS","EKH","ELT","SAN","GRV","HFY","CRF","TUK","SCA","MKA","LMY","LAF","IDP","BMT","WLO","NRO","RTE","CRN","HOM","SKN","SAC","DIL","DVL","VEC","CUT","SDL","DQN","TXA","SOL","WPT","GRA","TWO","SBY","FAY","SND","SOB","ROC","EXR","STW","LRC","BAL","SAR","LOD","MIN","MDN","CLF","GLM","RVR","SYR","HHL","WEM","REN","ALN","RSV","HNF","MID","KIS","GPK","SIM","NRK","AUS","ANA","GLN","DAV","LNS","RKV","EXT","JAN","SKY","MTZ","CML","FMT","LWA","NLC","ALP","MET","COX","WIP","LFT","EMY","DLD","VAN","RAT","KAL","CYN","BRO","FNO","KEE","ESM","WRJ","BRK","BLF","SCH","WLN","VRV","BUR","ALX","NSF","CPN","HOP","TCL","LNC","PAG","MVN","GNS","MAD","FED","KAN","SKT","HOS","WHL","GUA","PIC","BBY","FLN","WAC","DDG","NCR","VNC","SMT","OKE","DYE","RNO","GLE","RNK","COV","WNR","KTR","HIN","ALT","ATR","LAX","DET","WPK","BEL","MHL","MOD","HBG","WFD","CNL","TRM","DEM","PCT","OKC","BUF","MRC","POR","OKL","PSC","BFX","MAT","LPE","GAS","PUR","BWI","NHV","STS","SVT","RTL","NOL","TRE","WTH","SSM","GJT","HAS","TCA","TRI","MRB","GBB","TUS","WNL","VAC","HUN","ESX","ALD","OXN","WAS","SDY","PAK","DAL","HAM","HAV","QCY","GRI","GFD","JAX","ARB","STM","SPL","MCG","LNK","MCD","GSC","THN","QAN","LEW","NLS","WTN","ARK","SLO","MSS","DEN","CVS","LVW","WAB","CLA"]